apiVersion: v1
kind: Service
metadata:
    name: parachain
spec:
    type: { { .Values.service.type } }
    selector:
        app: parachain
    ports:
        - port: 30333
          targetPort: 30333
        - port: 9934
          targetPort: 9934
        - port: 9945
          targetPort: 9945
